name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r shakespeare_ml/requirements.txt
    - name: Run backend tests
      run: |
        cd backend
        pytest
    - name: Run ML tests
      run: |
        cd shakespeare_ml
        pytest
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Run frontend tests
      run: |
        cd frontend
        npm test

  build-and-prepare:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/CI/CD' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Build application
      run: |
        # cd frontend && npm run build
        # cd backend && python -m build
    - name: Create release package
      run: |
        # Crear un archivo zip con los artefactos construidos
        zip -r release.zip backend frontend shakespeare_ml
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
    - name: Generate release notes
      run: |
        echo "Release notes for version ${{ github.sha }}" > release_notes.md
        echo "Changes in this release:" >> release_notes.md
        git log -1 --pretty=format:"%s%n%b" >> release_notes.md
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body_path: release_notes.md
        draft: false
        prerelease: false